#! /bin/sh
# Maks' bspwm config

# hotkey daemon
sxhkd &
# compositor
compton --config ~/.compton.conf &

# configuration of bspwm itself

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config top_padding 23
bspc config border_width 4
bspc config window_gap 10
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config click_to_focus true 

bspc config normal_border_color "#383838"
bspc config focused_border_color "#a1b56c"
bspc config presel_feedback_color "#f7ca88"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# some quality of life stuff

# background; good indicator of whether or not bpswm is started too
~/wallpaper.sh &
# music server
sudo rc-service mpd restart &
# keymap
setxkbmap pl

# status panel TODO ; torn between lemonbar and dzen2
#.config/lemonbar/config | dzen2 -h 16 -fn 'Hack' -bg black -p &
~/src/Coding/bash/panel.sh | dzen2 -h 16 -fn 'Hack' -bg black -p
